### ISSUE TITLE
Traceback error in logs

### ISSUE THREAD

**Issue by seaverd** [allangood/rtlamr2mqtt#15] opened 2021-09-12 17:27 UTC
I am getting the following error in my logs:

today at 1:22:04 PM Traceback (most recent call last):
today at 1:22:04 PM   File "/usr/bin/rtlamr2mqtt.py", line 52, in <module>
today at 1:22:04 PM     for amrline in rtlamr.stdout:
today at 1:22:04 PM   File "/usr/bin/rtlamr2mqtt.py", line 14, in shutdown
today at 1:22:04 PM     mqtt_client.connect(host=mqtt_host, port=mqtt_port)
today at 1:22:04 PM NameError: name 'mqtt_client' is not defined
today at 1:22:04 PM Container stopped
today at 1:24:33 PM Container started
today at 1:22:04 PM NameError: name 'mqtt_client' is not defined
today at 1:24:33 PM Starting in DEBUG Mode...
today at 1:24:33 PM listening...
today at 1:24:35 PM {"Time":"2021-09-12T13:24:35.859423012-04:00","Offset":0,"Length":0,"Message":{"ID":37004912,"Type":4,"TamperPhy":0,"TamperEnc":1,"Consumption":48607,"ChecksumVal":13903}}

**Comment by allangood** [comment] 2021-09-13 21:30
Hello @seaverd ,

This error was caused by the now renamed from "DEBUG MODE" to "LISTEN_ONLY MODE".

If you want to get more verbose messages from your container, add a `verbosity: debug` into your general section configuration YAML file.

if you want to run your container in the LISTEN mode to catch all meters around you, run your container with `-e LISTEN_ONLY=yes`.

More information in the README page.

Fixed on #16 

Thank you!

**Closed by allangood** 2021-09-13 21:30 UTC
